In [1]:
%reload_kedro

[08/14/24 17:33:09] INFO     Resolved project path as: /Users/sharkovgrigory/code/fraud_detection.  ]8;id=53746;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=755934;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#171\171]8;;\
                             To set a different path, run '%reload_kedro <project_root>'                           

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=928075;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=938791;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py#65\65]8;;\

                    WARNING  No 'mlflow.yml' config file found in environment. Default            ]8;id=615070;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=61752;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py#78\78]8;;\
                             configuration will be used. Use ``kedro mlflow init`` command in CLI                  
                             to customize the configuration.                                                       

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=946051;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/config/kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=6415;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/config/kedro_mlflow_config.py#260\260]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is                             
                             converted to a valid uri:                                                             
                             'file:///Users/sharkovgrigory/code/fraud_detection/mlruns'                            

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=604064;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=415849;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_telemetry/plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If              
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`              
                             environment variables, or create a `.telemetry` file in the current                   
                             working directory with the contents `consent: false`. Read more at                    
                             https://docs.kedro.org/en/stable/configuration/telemetry.html                         

[08/14/24 17:33:10] INFO     Kedro project fraud_detection                                          ]8;id=711782;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=608630;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#141\141]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=99624;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=865892;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#142\142]8;;\
                             'pipelines'                                                                           

                    INFO     Registered line magic 'run_viz'                                        ]8;id=179458;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=514021;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#148\148]8;;\

In [2]:
from fraud_detection.utils.encoder_utils import get_row_preprocessor, FAST_MODEL_SETTINGS

In [3]:
train_data = catalog.load("combined_train_data")
id_cols = context.params.get("train_set_parameters").get("columns").get('id_columns')
cat_cols = ["merchant", "category"] #, "gender"]
num_cols = ["amt", 'city_pop']

train_data.head()

                    INFO     Loading data from combined_train_data (CSVDataset)...              ]8;id=467827;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=909058;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/io/data_catalog.py#508\508]8;;\

cc_num        window_id  label                              merchant  \
0  60416207185  60416207185_115   True    fraud_Schroeder, Hauck and Treutel   
1  60416207185  60416207185_115   True     fraud_Hills, Hegmann and Schaefer   
2  60416207185  60416207185_115   True  fraud_Langworth, Boehm and Gulgowski   
3  60416207185  60416207185_115   True              fraud_Turcotte-Halvorson   
4  60416207185  60416207185_115   True                   fraud_Padberg-Sauer   

         category     amt gender           city state  city_pop  \
0   entertainment   90.60      F  Fort Washakie    WY      1645   
1  health_fitness   26.13      F  Fort Washakie    WY      1645   
2    shopping_net    1.24      F  Fort Washakie    WY      1645   
3        misc_pos   11.60      F  Fort Washakie    WY      1645   
4            home  200.83      F  Fort Washakie    WY      1645   

                           job  
0  Information systems manager  
1  Information systems manager  
2  Information systems manager  
3  Information systems manager  
4  Information systems manager

In [4]:
preprocessor = get_row_preprocessor(cat_cols, num_cols, FAST_MODEL_SETTINGS)
preprocessor.fit(train_data)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 preprocessor = get_row_preprocessor(cat_cols, num_cols, FAST_MODEL_SETTINGS)                 │
│ ❱ 2 preprocessor.fit(train_data)                                                                 │
│   3                                                                                              │
│                                                                                                  │
│ /opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/sklearn/base.py:1473 in        │
│ wrapper                                                                                          │
│                                                                                                  │
│   1470 │   │   │   │   │   prefer_skip_nested_validation or global_skip_validation               │
│   1471 │   │   │   │   )                                                                         │
│   1472 │   │   │   ):                                                                            │
│ ❱ 1473 │   │   │   │   return fit_method(estimator, *args, **kwargs)                             │
│   1474 │   │                                                                                     │
│   1475 │   │   return wrapper                                                                    │
│   1476                                                                                           │
│                                                                                                  │
│ /opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/sklearn/pipeline.py:473 in fit │
│                                                                                                  │
│    470 │   │   with _print_elapsed_time("Pipeline", self._log_message(len(self.steps) - 1)):     │
│    471 │   │   │   if self._final_estimator != "passthrough":                                    │
│    472 │   │   │   │   last_step_params = routed_params[self.steps[-1][0]]                       │
│ ❱  473 │   │   │   │   self._final_estimator.fit(Xt, y, **last_step_params["fit"])               │
│    474 │   │                                                                                     │
│    475 │   │   return self                                                                       │
│    476                                                                                           │
│                                                                                                  │
│ /opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/sklearn/pipeline.py:1681 in    │
│ fit                                                                                              │
│                                                                                                  │
│   1678 │   │   │   │   routed_params[name] = Bunch(fit={})                                       │
│   1679 │   │   │   │   routed_params[name].fit = fit_params                                      │
│   1680 │   │                                                                                     │
│ ❱ 1681 │   │   transformers = self._parallel_func(X, y, _fit_one, routed_params)                 │
│   1682 │   │                                                                                     │
│   1683 │   │   if not transformers:                                                              │
│   1684 │   │   │   # All transformers are None                                                   │
│                                                                                                  │
│ /opt/miniconda3/envs/fraud_detection/lib/python3.11/site-pa

In [6]:
import pandas as pd
pd.DataFrame(
    preprocessor.transform(train_data.loc[:1]),
    #columns=cat_cols #, 'emb_gender']
)


0         1         2         3         4         5         6   \
0 -0.094870  0.396500  0.679532 -1.028078  0.957905 -0.768318  0.112542   
1 -5.215416  1.223808  0.948390 -1.491221  0.308472  2.670652  0.112542   

         7         8         9   ...        11   12   13   14        15  \
0  0.343385  0.242447 -4.302992  ... -1.848827  0.0  0.0  0.0 -4.166647   
1  0.343385  0.242447 -2.909857  ...  1.591855  0.0  0.0  0.0 -1.486815   

         16        17        18        19        20  
0 -0.074174  2.554254  0.000000  0.000000  0.000000  
1  5.788609 -2.490703 -2.860462  3.000796  4.294401  

[2 rows x 21 columns]

In [10]:
embedder_settings = {
    "vector_size": 3,
    "window": 5,
    "min_count": 3,
    "workers": 4,
}

cat_columns = ["merchant", "category"]

preprocessor = get_row_preprocessor(cat_columns, embedder_settings)

# Assuming df is your DataFrame with the columns "column1" and "column2"
preprocessor = preprocessor.fit(train_data)
preprocessor.transform(train_data.loc[:1,:])


array([[ 0.01186388,  0.65973073,  0.2925068 , -0.697257  ,  1.3188564 ,
        -1.4537454 ,  0.11684387,  0.34552673,  0.22169577, -4.270455  ,
         1.4948568 , -1.6351305 ,  0.        ,  0.        ,  0.        ,
        -4.2094793 , -0.14198299,  2.458057  ,  0.        ,  0.        ,
         0.        ],
       [-4.312101  ,  0.577466  ,  0.89631134, -1.0290817 ,  0.08379973,
         2.5354154 ,  0.11684387,  0.34552673,  0.22169577, -1.841812  ,
         0.08542699,  2.4859686 ,  0.        ,  0.        ,  0.        ,
        -1.4693879 ,  5.735981  , -2.3756335 , -2.6593707 ,  3.287538  ,
         4.196274  ]], dtype=float32)

In [8]:
preprocessor.transform(train_data.loc[:1])



array([[ 1.1939244 ,  0.8178266 ,  1.1012037 ,  0.7147421 ,  0.53418845,
        -0.14989288,  3.3618038 ,  3.6822762 ,  0.        ,  0.        ,
         3.2463214 ,  0.32967222,  0.        ,  0.        ],
       [ 0.35501963, -2.221231  ,  0.70940423, -0.7026621 ,  0.53418845,
        -0.14989288,  0.57608044, -0.2750211 ,  0.        ,  0.        ,
        -0.61291796,  6.4386973 ,  4.7903857 ,  1.1592278 ]],
      dtype=float32)

In [ ]:
columns = ["merchant", "category"]
text_embedders = []
for col in columns:
    _embedder = TextEmbedder(train_data[col], fast_model_settings)
    text_embedders.append(_embedder)

In [6]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.reshape, kw_args={"newshape": (-1,)})
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([0, 1, 2, 3])

In [11]:
from sklearn.impute import SimpleImputer