In [1]:
%reload_kedro

[08/14/24 20:16:30] INFO     Resolved project path as: /Users/sharkovgrigory/code/fraud_detection.  ]8;id=541253;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=259781;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#171\171]8;;\
                             To set a different path, run '%reload_kedro <project_root>'                           

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=388359;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=160425;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py#65\65]8;;\

                    WARNING  No 'mlflow.yml' config file found in environment. Default            ]8;id=567185;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=294756;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py#78\78]8;;\
                             configuration will be used. Use ``kedro mlflow init`` command in CLI                  
                             to customize the configuration.                                                       

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=2866;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/config/kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=320340;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_mlflow/config/kedro_mlflow_config.py#260\260]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is                             
                             converted to a valid uri:                                                             
                             'file:///Users/sharkovgrigory/code/fraud_detection/mlruns'                            

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=611685;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=581613;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro_telemetry/plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If              
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`              
                             environment variables, or create a `.telemetry` file in the current                   
                             working directory with the contents `consent: false`. Read more at                    
                             https://docs.kedro.org/en/stable/configuration/telemetry.html                         

                    INFO     Kedro project fraud_detection                                          ]8;id=913889;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=316857;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#141\141]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=274865;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=211592;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#142\142]8;;\
                             'pipelines'                                                                           

                    INFO     Registered line magic 'run_viz'                                        ]8;id=123048;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=219303;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/ipython/__init__.py#148\148]8;;\

In [2]:
from fraud_detection.utils.row_preprocessor import get_row_preprocessor, FAST_MODEL_SETTINGS

In [5]:
train_data = catalog.load("combined_train_data")
id_cols = context.params.get("train_set_parameters").get("columns").get('id_columns')
cat_cols = ["merchant", "category"] #, "gender"]
num_cols = ["amt", 'city_pop']

train_data.head()

[08/14/24 20:16:58] INFO     Loading data from combined_train_data (CSVDataset)...              ]8;id=805459;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=164887;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/kedro/io/data_catalog.py#508\508]8;;\

cc_num        window_id  label                              merchant  \
0  60416207185  60416207185_115   True    fraud_Schroeder, Hauck and Treutel   
1  60416207185  60416207185_115   True     fraud_Hills, Hegmann and Schaefer   
2  60416207185  60416207185_115   True  fraud_Langworth, Boehm and Gulgowski   
3  60416207185  60416207185_115   True              fraud_Turcotte-Halvorson   
4  60416207185  60416207185_115   True                   fraud_Padberg-Sauer   

         category     amt gender           city state  city_pop  \
0   entertainment   90.60      F  Fort Washakie    WY      1645   
1  health_fitness   26.13      F  Fort Washakie    WY      1645   
2    shopping_net    1.24      F  Fort Washakie    WY      1645   
3        misc_pos   11.60      F  Fort Washakie    WY      1645   
4            home  200.83      F  Fort Washakie    WY      1645   

                           job  
0  Information systems manager  
1  Information systems manager  
2  Information systems manager  
3  Information systems manager  
4  Information systems manager

In [6]:
preprocessor = get_row_preprocessor(cat_cols, num_cols, FAST_MODEL_SETTINGS)
preprocessor.fit(train_data)

[08/14/24 20:17:02] WARNING  Each 'sentences' item should be a list of words (usually unicode       ]8;id=984707;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/gensim/models/word2vec.py\word2vec.py]8;;\:]8;id=527286;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/gensim/models/word2vec.py#558\558]8;;\
                             strings). First item here is instead plain <class 'str'>.                             

[08/14/24 20:17:04] WARNING  Each 'sentences' item should be a list of words (usually unicode       ]8;id=754225;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/gensim/models/word2vec.py\word2vec.py]8;;\:]8;id=984364;file:///opt/miniconda3/envs/fraud_detection/lib/python3.11/site-packages/gensim/models/word2vec.py#558\558]8;;\
                             strings). First item here is instead plain <class 'str'>.                             

Pipeline(steps=[('combined_embeddings',
                 FeatureUnion(n_jobs=1,
                              transformer_list=[('encoder_pipeline_merchant',
                                                 Pipeline(steps=[('encoder_merchant',
                                                                  FastTextEncoder(column='merchant',
                                                                                  embedder_settings={'min_count': 3,
                                                                                                     'vector_size': 3,
                                                                                                     'window': 5,
                                                                                                     'workers': 4}))])),
                                                ('encoder_pipeline_category',
                                                 Pipeline(steps=[('encoder_category',
                                                                  FastTextEncoder(column='categ...
                                                                  FunctionTransformer(func=<function get_row_preprocessor.<locals>.<listcomp>.<lambda> at 0x316382c00>)),
                                                                 ('scaler_amt',
                                                                  StandardScaler()),
                                                                 ('imputer_amt',
                                                                  SimpleImputer())])),
                                                ('numeric_pipeline_city_pop',
                                                 Pipeline(steps=[('selector_city_pop',
                                                                  FunctionTransformer(func=<function get_row_preprocessor.<locals>.<listcomp>.<lambda> at 0x316382ca0>)),
                                                                 ('scaler_city_pop',
                                                                  StandardScaler()),
                                                                 ('imputer_city_pop',
                                                                  SimpleImputer())]))]))])

In [8]:
preprocessor.transform(train_data.loc[:1,:])


array([['-0.014516915 0.0045382995 0.014889569',
        '0.017116437 -0.082998045 0.0573985',
        '0.060293645 0.078404866 0.019872919',
        '-0.04159637 0.043534033 -0.0540257',
        '-0.002666257 0.024426937 -0.033753067', -0.29084700339951247,
        -0.29084700339951247],
       ['-0.08941088 0.059118245 0.04565257',
        '-0.030436808 -0.015588927 -0.07261914',
        '0.060293645 0.078404866 0.019872919',
        '0.011420587 -0.041980065 0.07569261',
        '0.0070926007 0.005174372 -0.017350368', -0.29084700339951247,
        -0.29084700339951247]], dtype=object)

In [10]:
embedder_settings = {
    "vector_size": 3,
    "window": 5,
    "min_count": 3,
    "workers": 4,
}

cat_columns = ["merchant", "category"]

preprocessor = get_row_preprocessor(cat_columns, embedder_settings)

# Assuming df is your DataFrame with the columns "column1" and "column2"
preprocessor = preprocessor.fit(train_data)
preprocessor.transform(train_data.loc[:1,:])


array([[ 0.01186388,  0.65973073,  0.2925068 , -0.697257  ,  1.3188564 ,
        -1.4537454 ,  0.11684387,  0.34552673,  0.22169577, -4.270455  ,
         1.4948568 , -1.6351305 ,  0.        ,  0.        ,  0.        ,
        -4.2094793 , -0.14198299,  2.458057  ,  0.        ,  0.        ,
         0.        ],
       [-4.312101  ,  0.577466  ,  0.89631134, -1.0290817 ,  0.08379973,
         2.5354154 ,  0.11684387,  0.34552673,  0.22169577, -1.841812  ,
         0.08542699,  2.4859686 ,  0.        ,  0.        ,  0.        ,
        -1.4693879 ,  5.735981  , -2.3756335 , -2.6593707 ,  3.287538  ,
         4.196274  ]], dtype=float32)

In [8]:
preprocessor.transform(train_data.loc[:1])



array([[ 1.1939244 ,  0.8178266 ,  1.1012037 ,  0.7147421 ,  0.53418845,
        -0.14989288,  3.3618038 ,  3.6822762 ,  0.        ,  0.        ,
         3.2463214 ,  0.32967222,  0.        ,  0.        ],
       [ 0.35501963, -2.221231  ,  0.70940423, -0.7026621 ,  0.53418845,
        -0.14989288,  0.57608044, -0.2750211 ,  0.        ,  0.        ,
        -0.61291796,  6.4386973 ,  4.7903857 ,  1.1592278 ]],
      dtype=float32)

In [ ]:
columns = ["merchant", "category"]
text_embedders = []
for col in columns:
    _embedder = TextEmbedder(train_data[col], fast_model_settings)
    text_embedders.append(_embedder)

In [6]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.reshape, kw_args={"newshape": (-1,)})
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([0, 1, 2, 3])

In [11]:
from sklearn.impute import SimpleImputer